# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "zh"

pipeline:
  - name: "JiebaTokenizer"
    dictionary_path: "data/jieba_userdict/jieba_userdict.txt"
  - name: "RegexFeaturizer"
  - name: "CountVectorsFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
  - name: FallbackClassifier
    threshold: 0.7
  - name: "DIETClassifier"


policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 200
  - name: RulePolicy
    core_fallback_threshold: 0.5
    core_fallback_action_name: 'action_default_fallback'
#  - name: FallbackPolicy
#    nlu_threshold: 0.6
#    core_threshold: 0.6
#    fallback_action_name: 'action_default_fallback'